print("ジャンルを入力して下さい")
genre  = input()
print("タイトルを入力して下さい")
title  = input()
print("感想を入力して下さい")
review = input()
line   = "\n---------------------------"

print("ジャンル : " + genre)
print(line)
print("タイトル : " + title)
print(line)
print("感想 :")
print(review)
print(line)
